var quote = ["Whatever the mind of man can conceive and believe, it can achieve.",
"Your time is limited, so don’t waste it living someone else’s life.",
"Strive not to be a success, but rather to be of value.",
"You miss 100% of the shots you don’t take.",
"Every strike brings me closer to the next home run.",
"Definiteness of purpose is the starting point of all achievement.",
"Life is what happens to you while you’re busy making other plans.",
"If you do what you’ve always done, you’ll get what you’ve always gotten.",
"The mind is everything. What you think you become.",
"The best time to plant a tree was 20 years ago. The second best time is now.",
"Eighty percent of success is showing up.",
"Don’t wait. The time will never be just right.",
"Winning isn’t everything, but wanting to win is.",
"You can never cross the ocean until you have the courage to lose sight of the shore.",
"Either you run the day, or the day runs you.",
"The two most important days in your life are the day you are born and the day you find out why.",
"Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.",
"Inspiration exists, but it must find you working.",
"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
"Obstacles are those frightful things you see when you take your eyes off the goal.",
"The only person you are destined to become is the person you decide to be.",
"Go confidently in the direction of your dreams.  Live the life you have imagined.",
"Certain things catch your eye, but pursue only those that capture the heart.",
"Believe you can and you’re halfway there.",
"Everything you’ve ever wanted is on the other side of fear.",
"Once you choose hope, anything’s possible.",
"Start where you are. Use what you have.  Do what you can.",
"Fall seven times and stand up eight.",
"Everything has beauty, but not everyone can see.",
"Happiness is not something readymade.  It comes from your own actions.",
"If the wind will not serve, take to the oars.",
"The way to get started is to quit talking and begin doing.",
"A person who never made a mistake never tried anything new.",
"There are no traffic jams along the extra mile.",
"It is never too late to be what you might have been.",
"You become what you believe.",
"Without deviation from the norm, progress is not possible.",
"It does not matter how slowly you go as long as you do not stop.",
"Remember that not getting what you want is sometimes a wonderful stroke of luck.",
"You can’t use up creativity.  The more you use, the more you have.",
"Dream big and dare to fail.",
"Do what you can, where you are, with what you have.",
"You may be disappointed if you fail, but you are doomed if you don’t try.",
"Life is what we make it, always has been, always will be.",
"Change your thoughts and you change your world.",
"Nothing is impossible, the word itself says, “I’m possible!”",
"The only way to do great work is to love what you do.",
"If you can dream it, you can achieve it.",
"We all have limits. Almost no one reaches theirs. You definitely haven’t.",
"Do it or not. There is no try.",
"Good things come to people who wait, but better things come to those who go out and get them.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"Just when the caterpillar thought the world was ending, he turned into a butterfly.",
"Opportunities don't happen, you create them.",
"If you're going through hell keep going.",
"Don't be afraid to give up the good to go for the great.",
"The starting point of all achievement is desire.",
"Success is the sum of small efforts, repeated day-in and day-out.",
"All progress takes place outside the comfort zone."]
